name: honkipass6
description: "Honkipass 6"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.0
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  flutter_svg: ^2.2.3
  flutter_riverpod: ^3.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  shared_preferences: ^2.5.3
  riverpod_annotation: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  riverpod_generator: ^3.0.3
  build_runner: ^2.7.1
flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Monospace
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
